const express = require('express');
const router = express.Router();

// AI responses (mock - replace with Gemini API in production)
const AI_RESPONSES = {
  explain: (topic) => `## ${topic} Explained\n\nThis is a comprehensive explanation of ${topic}. In a production environment, this would be generated by Google Gemini API with detailed, contextual content.\n\n### Key Concepts:\n1. Foundation principles\n2. Core mechanisms\n3. Practical applications\n\n💡 Ask me for more specific aspects!`,
  quiz: (topic) => `## Quiz: ${topic}\n\n**Q1:** What is a fundamental concept in ${topic}?\n- A) Option 1\n- B) Option 2 ✅\n- C) Option 3\n- D) Option 4\n\n**Q2:** Which best describes ${topic}?\n- A) Description 1\n- B) Description 2\n- C) Description 3 ✅\n- D) Description 4`,
  summarize: (text) => `## Summary\n\n${text.substring(0, 200)}...\n\n### Key Points:\n- Main idea extracted\n- Supporting details noted\n- Action items identified`,
  doubt: (text) => {
    const confusionWords = ['how', 'why', 'what', 'confused', 'help', 'stuck', 'understand', '?'];
    const hasConfusion = confusionWords.some(w => text.toLowerCase().includes(w));
    return { isDoubt: hasConfusion, confidence: hasConfusion ? 0.85 : 0.2, suggestion: hasConfusion ? 'It looks like you might need help. Would you like me to explain this concept?' : null };
  },
};

// POST /api/ai/chat - AI study assistant
router.post('/chat', (req, res) => {
  const { message, mode } = req.body;
  let response;
  switch (mode) {
    case 'explain': response = AI_RESPONSES.explain(message); break;
    case 'quiz': response = AI_RESPONSES.quiz(message); break;
    case 'summarize': response = AI_RESPONSES.summarize(message); break;
    default: response = `I received your message: "${message}"\n\nIn production, I'd use Google Gemini to give you a detailed answer. Try asking me to explain, quiz, or summarize a topic!`;
  }
  res.json({ response, mode: mode || 'chat' });
});

// POST /api/ai/summarize - Summarize chat
router.post('/summarize', (req, res) => {
  const { messages } = req.body;
  const text = Array.isArray(messages) ? messages.map(m => m.content || m).join('\n') : '';
  res.json({ summary: AI_RESPONSES.summarize(text) });
});

// POST /api/ai/detect-doubt - Detect if message is a doubt
router.post('/detect-doubt', (req, res) => {
  const { text } = req.body;
  res.json(AI_RESPONSES.doubt(text || ''));
});

module.exports = router;
